# --- START OF FILE constants.py ---
import os
import random
from paths import WALL_SPRITE_DIR, TREE_SPRITE_DIR

# --- Seed for Consistent Randomness ---
RANDOM_SEED = 1337
random.seed(RANDOM_SEED) # Seed should be set early


# --- Animation Speed ---
ANIMATION_SPEED_MS = 150 

# --- Screen & General ---
SCREEN_WIDTH = 1370
SCREEN_HEIGHT = 720
FPS = 60

# --- Player ---
PLAYER_RADIUS = 8
PLAYER_SPEED = 6
PLAYER_COLOR = (220, 0, 0)
# <<< Player Base Stats >>>
PLAYER_BASE_HEALTH = 100
PLAYER_BASE_DEFENSE = 0.05
PLAYER_BASE_AGILITY = 0.08
PLAYER_MAX_DEFENSE = 0.90
PLAYER_MAX_AGILITY = 0.60
# --- End Player Stats ---

# --- World & Camera ---
WORLD_WIDTH = 20000
WORLD_HEIGHT = 20000
SAVE_FILE_GRASS = "world_grass.pkl"

# --- Zone Definitions ---
FOREST_CENTER_X = WORLD_WIDTH // 2
FOREST_CENTER_Y = WORLD_HEIGHT // 3
FOREST_RADIUS_X = WORLD_WIDTH // 3
FOREST_RADIUS_Y = WORLD_HEIGHT // 5
FOREST_RADIUS_VARIATION = 800
FOREST_NUM_VERTICES = 80
KINGDOM_CENTER_X = WORLD_WIDTH // 5
KINGDOM_CENTER_Y = WORLD_HEIGHT // 2
KINGDOM_RADIUS = 3000
KINGDOM_RADIUS_VARIATION = 250
KINGDOM_NUM_VERTICES = 60

# --- Colors ---
GRASS_COLOR_BASE = (34, 139, 34)
FOREST_GROUND_COLOR = (0, 100, 0)
KINGDOM_GROUND_COLOR = (160, 160, 160)
PATH_COLOR = (190, 190, 190)
# Dungeon Colors (Imported from dungeon_gen originally, keep here for drawing)
DUNGEON_COLOR_FLOOR = (50, 50, 50)
DUNGEON_COLOR_WALL = (100, 100, 100)

# --- Detail Generation Constants ---
GRASS_DETAIL_COUNT = 10000
KINGDOM_BUILDING_COUNT = 45
KINGDOM_WALL_THICKNESS = 35 # Keep for collision rect generation
GATE_OPENING_WIDTH = 180
WALL_TILE_SIZE = 48 # Actual pixel dimension of wall sprites

WALL_AVOIDANCE_BUILDING = KINGDOM_WALL_THICKNESS * 2.5
WALL_AVOIDANCE_TREE = KINGDOM_WALL_THICKNESS * 2.0
PATH_WIDTH = 50
BUILDING_SPACING = 25
PATH_AVOIDANCE_RADIUS = PATH_WIDTH * 1.2
GATEHOUSE_SIZE = KINGDOM_WALL_THICKNESS * 1.8
TOWER_SIZE = KINGDOM_WALL_THICKNESS * 1.4

# --- Tree Sprite Constants ---
TREE_ASSET_PATH = os.path.join(TREE_SPRITE_DIR)
MIN_TREE_SPACING = 140
PDS_CANDIDATES = 15
TRUNK_COLLIDER_HEIGHT_MIN, TRUNK_COLLIDER_HEIGHT_MAX = 15, 25
TRUNK_COLLIDER_WIDTH_MIN, TRUNK_COLLIDER_WIDTH_MAX = 8, 14

# --- Structure Sprite Constants ----
WALL_SPRITE_BACK_PATH = os.path.join(WALL_SPRITE_DIR)

BUILDING_BASE_WIDTH_MIN, BUILDING_BASE_WIDTH_MAX = 40, 65
BUILDING_BASE_HEIGHT_MIN, BUILDING_BASE_HEIGHT_MAX = 35, 60

# --- Map Constants ---
MAP_WIDTH = 200
MAP_HEIGHT = MAP_WIDTH
MAP_X = SCREEN_WIDTH - MAP_WIDTH - 10
MAP_Y = 10
MAP_BG_COLOR = (100, 100, 100, 200)
MAP_BORDER_COLOR = (255, 255, 255)
MAP_PLAYER_COLOR = (255, 0, 0)
MAP_PLAYER_SIZE = 2
MAP_ZONE_FOREST_COLOR = (0, 80, 0, 180)
MAP_ZONE_KINGDOM_COLOR = (130, 130, 130, 180)
MAP_PATH_COLOR = (210, 210, 210, 200)
MAP_TOWER_COLOR = (60, 60, 60, 200)

# Quadtree Constants
QT_NODE_CAPACITY = 4
QT_MAX_DEPTH = 10

# Dungeon Constants (Imported from dungeon_gen originally)
# Need these for quadtree population and potentially drawing logic
DUNGEON_TILE_SIZE = 32
TILE_FLOOR = 0
TILE_WALL = 1
DUNGEON_GRID_WIDTH = 150 # Example, match dungeon_gen
DUNGEON_GRID_HEIGHT = 150 # Example, match dungeon_gen

# --- END OF FILE constants.py ---